spring.redis:
 host: localhost
 port: 6379
 password: null
 database: 0

colors:
 red: あか
 blue: あお

fruits:
 prices:
  apple: 150
  orange: 100

redis:
 url: "redis://localhost:6379/0"

# デフォルト値は"/actuator"
#  curl 'http://localhost:8080/admin/health'
management:
 endpoints:
  web:
   base-path: /admin